/*
 * Copyright (C) 2020 Nain57
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; If not, see <http://www.gnu.org/licenses/>.
 */
package com.buzbuz.smartautoclicker.database.room

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase

/**
 * Database for the clicks.
 *
 * Declare the singleton structure for the database as shown in Android Developer code lab in order to make it
 * available for the whole application. Application should uses the [ClickDao] to access it by using
 * [ClickDatabase.getDatabase] and then [ClickDatabase.clickDao].
 *
 * Actual implementation is automatically generated by AndroidX Room.
 */
@Database(
    entities = [
        ScenarioEntity::class,
        ClickEntity::class,
        ConditionEntity::class,
        ClickConditionCrossRef::class
    ],
    version = 1,
    exportSchema = true
)
abstract class ClickDatabase : RoomDatabase() {

    /** The data access object for the click database. */
    abstract fun clickDao(): ClickDao

    companion object {

        /** Singleton preventing multiple instances of database opening at the same time. */
        @Volatile
        private var INSTANCE: ClickDatabase? = null

        /**
         * Get the Room database singleton, or instantiates it if it wasn't yet.
         * <p>
         * @param context the Android context.
         * <p>
         * @return the Room database singleton.
         */
        fun getDatabase(context: Context): ClickDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    ClickDatabase::class.java,
                    "click_database")
                    .build()
                INSTANCE = instance
                instance
            }
        }
    }
}