name: Bug report
description: Create a report to help us improve
labels: ["bug"]
assignees:
  - Nain57
body:
  - type: input
    id: app-version
    attributes:
      label: Version of Smart AutoClicker
      placeholder: "3.0.1"
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Apk
      description: Installation source. No support is provided on other installation sources and the code itself
      options:
        - PlayStore
        - F-Droid
        - Github
      default: 0
    validations:
      required: true

  - type: input
    id: device-type
    attributes:
      label: Device brand and model
      placeholder: OnePlus 10 Pro
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Version of your Android OS
      description: Can usually be found under Settings -> About -> Versions
      placeholder: "14"
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What kind of bug have you encountered ?
      options:
        - Smart scenario
        - Backup
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe what happened?
      description: |
        Describe precise steps to reproduce the issue with bullet points. You must also attach screenshots/video showing how to reproduce it. \
        If your issue is about the behaviour of a condition/action/event, attach a scenario backup zip file with the minimal \
        elements to reproduce the bug.
      placeholder: Tell us what's wrong!
    validations:
      required: true

  - type: textarea
    id: what-should-happened
    attributes:
      label: Describe what should have happened?
      description: Describe what you expect to happen
      placeholder: Tell us own you think the application should have reacted
    validations:
      required: true

  - type: checkboxes
    id: duplicate
    attributes:
      label: Is it a duplicate?
      description: |
        I have checked if this bug was not already requested in another ticket. \
        [List of all opened bugs](https://github.com/Nain57/Smart-AutoClicker/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug)
        
      options:
        - label: There is no duplicates
          required: true

  - type: checkboxes
    id: attachements
    attributes:
      label: Did you provide enough information?
      description: |
        In order for the developpers to find the issue, must provide as much data as possible., and always attach screenshots/video of the bug. \
        If you think there is a bug in the scenario execution, you must always provide a minimal scenario to reproduce it, not your complete 100 events 1K conditions scenario. \
        If you think there is a bug with a scenario backup import, you must always provide the problematic scenario zip file. \
        Any ticket with not enough information will be automatically closed.
        
      options:
        - label: I have attached the required files
          required: true
