/*
 * Copyright (C) 2025 Kevin Buzeau
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.buzbuz.smartautoclicker.core.detection.data

import android.graphics.Point
import android.graphics.Rect
import androidx.annotation.RawRes

import com.buzbuz.smartautoclicker.core.detection.NumberFormatType
import com.buzbuz.smartautoclicker.core.detection.test.R

/**
 * Describe the images used for the tests.
 *
 * @param fileRes the resource of the raw image file. Must be generated using the Klickr screen capture.
 * @param size the size of the image, in pixels.
 */
internal sealed class TestImage(@field:RawRes val fileRes: Int, val size: Point) {

    /** Describe the images used as screen capture. */
    sealed class Screen(fileRes: Int, size: Point) : TestImage(fileRes, size) {

        data object TutorialWithTarget : Screen(
            fileRes = R.raw.screen_1,
            size = Point(1344, 2992)
        )
    }

    /**
     * Describe the image used as condition images.
     * @param expectedResults map of [Screen] images their expected result with this condition.
     */
    sealed class Condition(
        fileRes: Int,
        size: Point,
        val expectedResults: Map<Screen, ExpectedDetectionResults>,
    ) : TestImage(fileRes, size) {

        data object TutorialTargetBlue : Condition(
            fileRes = R.raw.condition_1,
            size = Point(198, 192),
            expectedResults = mapOf(
                Screen.TutorialWithTarget to ExpectedDetectionResults(
                    centerPosition = Point(672, 1696),
                    quality = 0.9750,
                ),
            )
        )

        data object TutorialTargetGrayscale : Condition(
            fileRes = R.raw.condition_1_grayscale,
            size = Point(198, 192),
            expectedResults = emptyMap(),
        )
    }

    /**
     * Screen capture containing all number detection test cases stacked vertically.
     * Generated by NumberBitmapGenerator; each row is 107px tall with 20px gaps between rows.
     * Use [numberTestCases] to get the detection area and expected value for each case.
     */
    data object NumberConditionsScreen : TestImage(
        fileRes = R.raw.screen_text_conditions,
        size = Point(417, 869),
    ) {
        val numberTestCases: List<NumberTestCase> = listOf(
            NumberTestCase(detectionArea = rowRect(0),  expectedValue = 42.0,          numberFormatType = NumberFormatType.AUTO),
            NumberTestCase(detectionArea = rowRect(1),  expectedValue = 42.5,          numberFormatType = NumberFormatType.DOT_DECIMAL),
            NumberTestCase(detectionArea = rowRect(2),  expectedValue = 42.5,          numberFormatType = NumberFormatType.COMMA_DECIMAL),
            NumberTestCase(detectionArea = rowRect(3),  expectedValue = 42.588,        numberFormatType = NumberFormatType.DOT_DECIMAL),
            NumberTestCase(detectionArea = rowRect(4),  expectedValue = 42.588,        numberFormatType = NumberFormatType.COMMA_DECIMAL),
            NumberTestCase(detectionArea = rowRect(5),  expectedValue = 1_234_567.890, numberFormatType = NumberFormatType.COMMA_DECIMAL),
            NumberTestCase(detectionArea = rowRect(6),  expectedValue = 1_234_567.890, numberFormatType = NumberFormatType.DOT_DECIMAL),
        )

        private fun rowRect(index: Int): Rect {
            val rowHeight = 107
            val rowGap    = 20
            val top = index * (rowHeight + rowGap)
            return Rect(0, top, size.x, top + rowHeight)
        }
    }
}

internal data class ExpectedDetectionResults(
    val centerPosition: Point,
    val quality: Double,
)

internal data class NumberTestCase(
    val detectionArea: Rect,
    val expectedValue: Double,
    val numberFormatType: NumberFormatType,
)
