/*
 * Copyright (C) 2024 Kevin Buzeau
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.buzbuz.smartautoclicker.core.common.tutorial.domain.model.monitoring

enum class MonitoredViewType {
    ACTION_TYPE_DIALOG_CLICK_ACTION,
    ACTIONS_BRIEF_FIRST_ITEM,
    ACTIONS_BRIEF_MENU_BUTTON_CREATE_ACTION,
    ACTIONS_BRIEF_MENU_BUTTON_SAVE,
    CLICK_DIALOG_BUTTON_SAVE,
    CLICK_DIALOG_FIELD_POSITION_TYPE_ITEM_ON_CONDITION,
    CLICK_DIALOG_FIELD_SELECT_POSITION_OR_CONDITION,

    CONDITION_SELECTOR_DIALOG_ITEM_FIRST,
    CONDITIONS_BRIEF_FIRST_ITEM,
    CONDITIONS_BRIEF_MENU_BUTTON_CREATE,
    CONDITIONS_BRIEF_MENU_BUTTON_SAVE,
    EVENT_DIALOG_BUTTON_SAVE,
    EVENT_DIALOG_FIELD_ACTIONS,
    EVENT_DIALOG_FIELD_CONDITIONS,
    EVENT_DIALOG_FIELD_OPERATOR_ITEM_AND,
    MAIN_MENU_BUTTON_CONFIG,
    MAIN_MENU_BUTTON_PLAY,
    SCENARIO_DIALOG_BUTTON_CREATE_EVENT,
    SCENARIO_DIALOG_BUTTON_SAVE,
    SCENARIO_DIALOG_ITEM_FIRST_EVENT,
    SCENARIO_DIALOG_TRIGGER_EVENT_TAB,

    SCREEN_CONDITION_CAPTURE_MENU_BUTTON_CAPTURE,
    SCREEN_CONDITION_DIALOG_BUTTON_SAVE,
    SCREEN_CONDITION_DIALOG_FIELD_TYPE_ITEM_IN_AREA,
    SCREEN_CONDITION_DIALOG_FIELD_AREA_SELECTOR,
    SCREEN_CONDITION_DIALOG_FIELD_VISIBILITY,

    SCREEN_CONDITION_TYPE_SELECTION_COLOR,
    SCREEN_CONDITION_TYPE_SELECTION_IMAGE,
    SCREEN_CONDITION_TYPE_SELECTION_NUMBER,
    SCREEN_CONDITION_TYPE_SELECTION_TEXT,

    TEXT_CONDITION_DIALOG_BUTTON_SAVE,
    TEXT_CONDITION_DIALOG_FIELD_AREA_SELECTOR,
    TEXT_CONDITION_DIALOG_FIELD_TEXT_TO_DETECT,

    TIMER_REACHED_CONDITION_BUTTON_SAVE,
    TIMER_REACHED_CONDITION_FIELD_AFTER,
    TIMER_REACHED_CONDITION_FIELD_RESTART,

    TRIGGER_CONDITION_LIST_DIALOG_BUTTON_CLOSE,
    TRIGGER_CONDITION_LIST_DIALOG_BUTTON_CREATE,

    TRIGGER_CONDITION_TYPE_ON_TIMER_REACHED,
    TRIGGER_CONDITION_TYPE_ON_BROADCAST_RECEIVED,
    TRIGGER_CONDITION_TYPE_ON_COUNTER_REACHED,

    NUMBER_CONDITION_DIALOG_BUTTON_SAVE,
    NUMBER_CONDITION_DIALOG_FIELD_AREA_SELECTOR,
    NUMBER_CONDITION_DIALOG_FIELD_OPERATOR_DROPDOWN,
    NUMBER_CONDITION_DIALOG_FIELD_OPERATOR_DROPDOWN_ITEM_GREATER,
    NUMBER_CONDITION_DIALOG_FIELD_OPERATOR_ITEM_GREATER,
    NUMBER_CONDITION_DIALOG_FIELD_VALUE_TO_DETECT,
}

