
package com.buzbuz.smartautoclicker.core.ui.monitoring

enum class MonitoredViewType {
    ACTION_TYPE_DIALOG_CLICK_ACTION,
    ACTIONS_BRIEF_FIRST_ITEM,
    ACTIONS_BRIEF_MENU_BUTTON_CREATE_ACTION,
    ACTIONS_BRIEF_MENU_BUTTON_SAVE,
    CLICK_DIALOG_BUTTON_SAVE,
    CLICK_DIALOG_FIELD_POSITION_TYPE_ITEM_ON_CONDITION,
    CLICK_DIALOG_FIELD_SELECT_POSITION_OR_CONDITION,
    CONDITION_CAPTURE_MENU_BUTTON_CAPTURE,
    CONDITION_DIALOG_BUTTON_SAVE,
    CONDITION_DIALOG_FIELD_TYPE_ITEM_WHOLE_SCREEN,
    CONDITION_SELECTOR_DIALOG_ITEM_FIRST,
    CONDITIONS_BRIEF_FIRST_ITEM,
    CONDITIONS_BRIEF_MENU_BUTTON_CREATE,
    CONDITIONS_BRIEF_MENU_BUTTON_SAVE,
    EVENT_DIALOG_BUTTON_SAVE,
    EVENT_DIALOG_FIELD_ACTIONS,
    EVENT_DIALOG_FIELD_CONDITIONS,
    EVENT_DIALOG_FIELD_OPERATOR_ITEM_AND,
    MAIN_MENU_BUTTON_CONFIG,
    MAIN_MENU_BUTTON_PLAY,
    SCENARIO_DIALOG_BUTTON_CREATE_EVENT,
    SCENARIO_DIALOG_BUTTON_SAVE,
    SCENARIO_DIALOG_ITEM_FIRST_EVENT,
}

